#!/bin/sh
# 备份dotfile到git项目目录下面
GIT_HOME="/home/cxc/workspace/git/dotfile"
# vim
cp -r $HOME/.vim        $GIT_HOME/vim/

# awesome
cp -r $HOME/.config/awesome/rc.lua      $GIT_HOME/awesome/
cp -r /usr/share/awesome/*              $GIT_HOME/awesome/

# shell
cp -r /usr/bin/refresh                  $GIT_HOME/shell/
cp -r /usr/bin/dotfilebackup            $GIT_HOME/shell/

# oh-my-zsh
cp -r $HOME/.zshrc                      $GIT_HOME/oh-my-zsh/

cd $GIT_HOME
git add .
git commit -m "`date +"%Y-%m-%d %H:%M:%S"` backup"
git push
